//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostDestek.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public Nullable<int> PostId { get; set; }
        public string Comment1 { get; set; }
        public int MemberId { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<int> Like { get; set; }
        public Nullable<int> Dislike { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Post Post { get; set; }
    }
}
