//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostDestek.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int PostId { get; set; }
        public Nullable<int> TopicId { get; set; }
        public string Title { get; set; }
        public Nullable<int> AnimalId { get; set; }
        public string Post1 { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> View { get; set; }
        public Nullable<int> Like { get; set; }
        public Nullable<int> Dislike { get; set; }
        public Nullable<int> CommentNum { get; set; }
    
        public virtual Animal Animal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Member Member { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
