//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostDestek.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veteriner
    {
        public int VetId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string PersonName { get; set; }
        public string VetName { get; set; }
        public string VetTelNo { get; set; }
        public string VetCommName { get; set; }
        public string VetAddress { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
